name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dopp1e
          template: classic
          # base: header, activity, repositories, metadata
          # base_indepth: yes
          # commits_authoring: aegiruchan@gmail.com,doppie@google.sex.pl,qdoppie@gmail.com
          # repositories_skipped: KubekZTwoimNadrukiem/BiznesElektroniczny
          # config_timezone: Europe/Warsaw
          # plugin_followup: yes
          # plugin_followup_archived: yes
          # plugin_followup_indepth: yes
          # plugin_followup_sections: user
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 0
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size,percentage,lines
          plugin_languages_ignored: ShaderLab
          repositories_affiliations: owner,collaborator
          repositories_forks: yes
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
