name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dopp1e
          template: classic
          base:
          # base_indepth: yes
          commits_authoring: aegiruchan@gmail.com,doppie@google.sex.pl,qdoppie@gmail.com
          repositories_skipped: KubekZTwoimNadrukiem/BiznesElektroniczny
          config_timezone: Europe/Warsaw
          # plugin_followup: yes
          # plugin_followup_archived: yes
          # plugin_followup_indepth: yes
          # plugin_followup_sections: user
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 0
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size,percentage,lines
          plugin_languages_ignored: ShaderLab
          repositories_affiliations: owner,collaborator
          repositories_forks: yes
          #output_action: pull-request-merge
          config_output: json
    # Run the main.go script to generate the README.md
  generate-readme:
    runs-on: ubuntu-latest
    needs: github-metrics
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Generate README.md
        run: |
          echo "Generating README.md..."
          go run main.go
      - name: Commit and push changes
        run: |
          git config --global user.name 'dopp1e'
          git config --global user.email 'qdoppie@gmail.com'
          git commit -am "Automated README.md update"
          git push
